apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: back
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
        - env:
            - name: BASE_URL
          image: "{{ .Values.back.image }}:{{ .Values.tag }}"
          name: back
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /application/src/media
              name: media-data
            - mountPath: /application/src/static
              name: static-data
            - mountPath: /application/src/project/fixtures
              name: back-claim2
      restartPolicy: Always
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
        - name: static-data
          persistentVolumeClaim:
            claimName: static-data
        - name: back-claim2
          persistentVolumeClaim:
            claimName: back-claim2
status: {}
