apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: DOMAIN
              value: {{ .Values.domain }}
          image: "{{ .Values.nginx.image }}:{{ .Values.tag }}"
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /var/www/front
              name: nginx-claim0
            - mountPath: /var/www/media
              name: media-data
            - mountPath: /var/www/static
              name: static-data
      restartPolicy: Always
      volumes:
        - name: nginx-claim0
          persistentVolumeClaim:
            claimName: nginx-claim0
        - name: media-data
          persistentVolumeClaim:
            claimName: media-data
        - name: static-data
          persistentVolumeClaim:
            claimName: static-data
status: {}
